Implemented fix for released monetdb-jdbc-3.0.jre8.jar and monetdb-mcl-1.19.jre8.jar when it is was run using java build 1.8.0_###. It would throw:  java.lang.NoSuchMethodError: java.nio.CharBuffer.mark()Ljava/nio/CharBuffer;i  at org.monetdb.mcl.parser.StartOfHeaderParser.getNextAsString(Unknown Source)  at org.monetdb.jdbc.MonetConnection$ResponseList.executeQuery(Unknown Source)  at org.monetdb.jdbc.MonetConnection$ResponseList.processQuery(Unknown Source)  at org.monetdb.jdbc.MonetStatement.internalExecute(Unknown Source)  at org.monetdb.jdbc.MonetStatement.execute(Unknown Source) The problem is caused by a change in java.nio.CharBuffer API (return types of methods mark() and reset() have changed from Buffer to CharBuffer) from Java 8 to Java 9+.